name: Compile proto files

on:
  workflow_dispatch:
    inputs:
      python:
        required: true
        type: choice
        description: "Python: compile and/or commit"
        options:
          - "none"
          - "compile"
          - "commit"
          - "compile+commit"

      cpp:
        required: true
        type: choice
        description: "C++: compile and/or commit"
        options:
          - "none"
          - "compile"
          - "commit"
          - "compile+commit"

      csharp:
        required: true
        type: choice
        description: "C#: compile and/or commit"
        options:
          - "none"
          - "compile"
          - "commit"
          - "compile+commit"

      ruby:
        required: true
        type: choice
        description: "Ruby: compile and/or commit"
        options:
          - "none"
          - "compile"
          - "commit"
          - "compile+commit"

      nodejs:
        required: true
        type: choice
        description: "Node.js: compile and/or commit"
        options:
          - "none"
          - "compile"
          - "commit"
          - "compile+commit"

      typescript:
        required: true
        type: choice
        description: "TypeScript: compile and/or commit"
        options:
          - "none"
          - "compile"
          - "commit"
          - "compile+commit"

jobs:
  Python:
    if: ${{ contains(github.event.inputs.python, 'compile') }}
    name: Compile proto files to python source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          pip install grpcio grpcio-tools

      - name: Compile
        run: |
          python compile.py python

      - name: Tree
        run: |
          tree

      - name: Commit and Push Changes
        if: ${{ contains(github.event.inputs.python, 'commit') }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "compile: proto files compiled"
            git push
          fi

  Cpp:
    if: ${{ contains(github.event.inputs.cpp, 'compile') }}
    name: Compile proto files to c++ source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Pre-requisites
        run: |
          cd $HOME
          mkdir grpc
          cd grpc
          wget https://github.com/XVGuardian/grpc-compiled/releases/download/v1.61.0/local_directory.zip
          unzip local_directory.zip
          tree .local
          export PATH="$HOME/grpc/.local/bin:$PATH"

      - name: Compile
        run: |
          export PATH="$HOME/grpc/.local/bin:$PATH"
          python compile.py cpp

      - name: Tree
        run: |
          tree

      - name: Commit and Push Changes
        if: ${{ contains(github.event.inputs.cpp, 'commit') }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "compile: proto files compiled"
            git push
          fi

  Csharp:
    if: ${{ contains(github.event.inputs.csharp, 'compile') }}
    name: Compile proto files to csharp source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Pre-requisites
        run: |
          cd $HOME
          mkdir grpc
          cd grpc
          wget https://github.com/XVGuardian/grpc-compiled/releases/download/v1.61.0/local_directory.zip
          unzip local_directory.zip
          tree .local
          export PATH="$HOME/grpc/.local/bin:$PATH"

      - name: Compile
        run: |
          export PATH="$HOME/grpc/.local/bin:$PATH"
          python compile.py csharp

      - name: Tree
        run: |
          tree

      - name: Commit and Push Changes
        if: ${{ contains(github.event.inputs.csharp, 'commit') }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "compile: proto files compiled"
            git push
          fi

  Ruby:
    if: ${{ contains(github.event.inputs.ruby, 'compile') }}
    name: Compile proto files to ruby source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Pre-requisites
        run: |
          cd $HOME
          mkdir grpc
          cd grpc
          wget https://github.com/XVGuardian/grpc-compiled/releases/download/v1.61.0/local_directory.zip
          unzip local_directory.zip
          tree .local
          export PATH="$HOME/grpc/.local/bin:$PATH"

      - name: Compile
        run: |
          export PATH="$HOME/grpc/.local/bin:$PATH"
          python compile.py ruby

      - name: Tree
        run: |
          tree

      - name: Commit and Push Changes
        if: ${{ contains(github.event.inputs.ruby, 'commit') }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "compile: proto files compiled"
            git push
          fi

  Nodejs:
    if: ${{ contains(github.event.inputs.nodejs, 'compile') }}
    name: Compile proto files to nodejs source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          npm install grpc-tools grpc
          npm install -g protoc-gen-ts

      - name: Install Pre-requisites
        run: |
          cd $HOME
          mkdir grpc
          cd grpc
          wget https://github.com/XVGuardian/grpc-compiled/releases/download/v1.61.0/local_directory.zip
          unzip local_directory.zip
          tree .local
          export PATH="$HOME/grpc/.local/bin:$PATH"

      - name: Compile
        run: |
          export PATH="$HOME/grpc/.local/bin:$PATH"
          python compile.py nodejs

      - name: Tree
        run: |
          tree

      - name: Commit and Push Changes
        if: ${{ contains(github.event.inputs.nodejs, 'commit') }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "compile: proto files compiled"
            git push
          fi

  TypeScript:
    if: ${{ contains(github.event.inputs.typescript, 'compile') }}
    name: Compile proto files to typescript source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.3"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          npm install -g protoc-gen-ts

      - name: Compile
        run: |
          python compile.py typescript

      - name: Tree
        run: |
          tree

      - name: Commit and Push Changes
        if: ${{ contains(github.event.inputs.typescript, 'commit') }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "compile: proto files compiled"
            git push
          fi
